// generated by argen; DO NOT EDIT
package db

import (
	"fmt"

	"github.com/monochromegane/argen"
)

type GroupRelation struct {
	src *Group
	*ar.Relation
}

func (m *Group) newRelation() *GroupRelation {
	r := &GroupRelation{
		m,
		ar.NewRelation(db, logger).Table("groups"),
	}
	r.Select(
		"id",
		"name",
		"path",
		"created_at",
		"updated_at",
	)

	return r
}

func (m Group) Select(columns ...string) *GroupRelation {
	return m.newRelation().Select(columns...)
}

func (r *GroupRelation) Select(columns ...string) *GroupRelation {
	cs := []string{}
	for _, c := range columns {
		if r.src.isColumnName(c) {
			cs = append(cs, fmt.Sprintf("groups.%s", c))
		} else {
			cs = append(cs, c)
		}
	}
	r.Relation.Columns(cs...)
	return r
}

func (m Group) Find(id int) (*Group, error) {
	return m.newRelation().Find(id)
}

func (r *GroupRelation) Find(id int) (*Group, error) {
	return r.FindBy("id", id)
}

func (m Group) FindBy(cond string, args ...interface{}) (*Group, error) {
	return m.newRelation().FindBy(cond, args...)
}

func (r *GroupRelation) FindBy(cond string, args ...interface{}) (*Group, error) {
	return r.Where(cond, args...).Limit(1).QueryRow()
}

func (m Group) First() (*Group, error) {
	return m.newRelation().First()
}

func (r *GroupRelation) First() (*Group, error) {
	return r.Order("id", "ASC").Limit(1).QueryRow()
}

func (m Group) Last() (*Group, error) {
	return m.newRelation().Last()
}

func (r *GroupRelation) Last() (*Group, error) {
	return r.Order("id", "DESC").Limit(1).QueryRow()
}

func (m Group) Where(cond string, args ...interface{}) *GroupRelation {
	return m.newRelation().Where(cond, args...)
}

func (r *GroupRelation) Where(cond string, args ...interface{}) *GroupRelation {
	r.Relation.Where(cond, args...)
	return r
}

func (r *GroupRelation) And(cond string, args ...interface{}) *GroupRelation {
	r.Relation.And(cond, args...)
	return r
}

func (m Group) Order(column, order string) *GroupRelation {
	return m.newRelation().Order(column, order)
}

func (r *GroupRelation) Order(column, order string) *GroupRelation {
	r.Relation.OrderBy(column, order)
	return r
}

func (m Group) Limit(limit int) *GroupRelation {
	return m.newRelation().Limit(limit)
}

func (r *GroupRelation) Limit(limit int) *GroupRelation {
	r.Relation.Limit(limit)
	return r
}

func (m Group) Offset(offset int) *GroupRelation {
	return m.newRelation().Offset(offset)
}

func (r *GroupRelation) Offset(offset int) *GroupRelation {
	r.Relation.Offset(offset)
	return r
}

func (m Group) Group(group string, groups ...string) *GroupRelation {
	return m.newRelation().Group(group, groups...)
}

func (r *GroupRelation) Group(group string, groups ...string) *GroupRelation {
	r.Relation.GroupBy(group, groups...)
	return r
}

func (r *GroupRelation) Having(cond string, args ...interface{}) *GroupRelation {
	r.Relation.Having(cond, args...)
	return r
}

func (m Group) IsValid() (bool, *ar.Errors) {
	result := true
	errors := &ar.Errors{}
	var on ar.On
	if m.IsNewRecord() {
		on = ar.OnCreate()
	} else {
		on = ar.OnUpdate()
	}
	rules := map[string]*ar.Validation{}
	for name, rule := range rules {
		if ok, errs := ar.NewValidator(rule).On(on).IsValid(m.fieldValueByName(name)); !ok {
			result = false
			errors.SetErrors(name, errs)
		}
	}
	customs := []*ar.Validation{}
	for _, rule := range customs {
		custom := ar.NewValidator(rule).On(on).Custom()
		custom(errors)
	}
	if len(errors.Messages) > 0 {
		result = false
	}
	return result, errors
}

type GroupParams Group

func (m Group) Build(p GroupParams) *Group {
	return &Group{
		ID:        p.ID,
		Name:      p.Name,
		Path:      p.Path,
		CreatedAt: p.CreatedAt,
		UpdatedAt: p.UpdatedAt,
	}
}

func (m Group) Create(p GroupParams) (*Group, *ar.Errors) {
	n := m.Build(p)
	_, errs := n.Save()
	return n, errs
}

func (m *Group) IsNewRecord() bool {
	return ar.IsZero(m.ID)
}

func (m *Group) IsPersistent() bool {
	return !m.IsNewRecord()
}

func (m *Group) Save(validate ...bool) (bool, *ar.Errors) {
	if len(validate) == 0 || len(validate) > 0 && validate[0] {
		if ok, errs := m.IsValid(); !ok {
			return false, errs
		}
	}
	errs := &ar.Errors{}
	if m.IsNewRecord() {
		ins := ar.NewInsert(db, logger).Table("groups").Params(map[string]interface{}{
			"name":       m.Name,
			"path":       m.Path,
			"created_at": m.CreatedAt,
			"updated_at": m.UpdatedAt,
		})

		if result, err := ins.Exec(); err != nil {
			errs.AddError("base", err)
			return false, errs
		} else {
			if lastId, err := result.LastInsertId(); err == nil {
				m.ID = int(lastId)
			}
		}
		return true, nil
	} else {
		upd := ar.NewUpdate(db, logger).Table("groups").Params(map[string]interface{}{
			"id":         m.ID,
			"name":       m.Name,
			"path":       m.Path,
			"created_at": m.CreatedAt,
			"updated_at": m.UpdatedAt,
		}).Where("id", m.ID)

		if _, err := upd.Exec(); err != nil {
			errs.AddError("base", err)
			return false, errs
		}
		return true, nil
	}
}

func (m *Group) Update(p GroupParams) (bool, *ar.Errors) {

	if !ar.IsZero(p.ID) {
		m.ID = p.ID
	}
	if !ar.IsZero(p.Name) {
		m.Name = p.Name
	}
	if !ar.IsZero(p.Path) {
		m.Path = p.Path
	}
	if !ar.IsZero(p.CreatedAt) {
		m.CreatedAt = p.CreatedAt
	}
	if !ar.IsZero(p.UpdatedAt) {
		m.UpdatedAt = p.UpdatedAt
	}
	return m.Save()
}

func (m *Group) UpdateColumns(p GroupParams) (bool, *ar.Errors) {

	if !ar.IsZero(p.ID) {
		m.ID = p.ID
	}
	if !ar.IsZero(p.Name) {
		m.Name = p.Name
	}
	if !ar.IsZero(p.Path) {
		m.Path = p.Path
	}
	if !ar.IsZero(p.CreatedAt) {
		m.CreatedAt = p.CreatedAt
	}
	if !ar.IsZero(p.UpdatedAt) {
		m.UpdatedAt = p.UpdatedAt
	}
	return m.Save(false)
}

func (m *Group) Destroy() (bool, *ar.Errors) {
	return m.Delete()
}

func (m *Group) Delete() (bool, *ar.Errors) {
	errs := &ar.Errors{}
	if _, err := ar.NewDelete(db, logger).Table("groups").Where("id", m.ID).Exec(); err != nil {
		errs.AddError("base", err)
		return false, errs
	}
	return true, nil
}

func (m Group) DeleteAll() (bool, *ar.Errors) {
	errs := &ar.Errors{}
	if _, err := ar.NewDelete(db, logger).Table("groups").Exec(); err != nil {
		errs.AddError("base", err)
		return false, errs
	}
	return true, nil
}

func (r *GroupRelation) Query() ([]*Group, error) {
	rows, err := r.Relation.Query()
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	results := []*Group{}
	for rows.Next() {
		row := &Group{}
		err := rows.Scan(row.fieldPtrsByName(r.Relation.GetColumns())...)
		if err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	return results, nil
}

func (r *GroupRelation) QueryRow() (*Group, error) {
	row := &Group{}
	err := r.Relation.QueryRow(row.fieldPtrsByName(r.Relation.GetColumns())...)
	if err != nil {
		return nil, err
	}
	return row, nil
}

func (m Group) Exists() bool {
	return m.newRelation().Exists()
}

func (m Group) Count(column ...string) int {
	return m.newRelation().Count(column...)
}

func (m Group) All() *GroupRelation {
	return m.newRelation().All()
}

func (r *GroupRelation) All() *GroupRelation {
	return r
}

func (m *Group) fieldValueByName(name string) interface{} {
	switch name {
	case "id", "groups.id":
		return m.ID
	case "name", "groups.name":
		return m.Name
	case "path", "groups.path":
		return m.Path
	case "created_at", "groups.created_at":
		return m.CreatedAt
	case "updated_at", "groups.updated_at":
		return m.UpdatedAt
	default:
		return ""
	}
}

func (m *Group) fieldPtrByName(name string) interface{} {
	switch name {
	case "id", "groups.id":
		return &m.ID
	case "name", "groups.name":
		return &m.Name
	case "path", "groups.path":
		return &m.Path
	case "created_at", "groups.created_at":
		return &m.CreatedAt
	case "updated_at", "groups.updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *Group) fieldPtrsByName(names []string) []interface{} {
	fields := []interface{}{}
	for _, n := range names {
		f := m.fieldPtrByName(n)
		fields = append(fields, f)
	}
	return fields
}

func (m *Group) isColumnName(name string) bool {
	for _, c := range m.columnNames() {
		if c == name {
			return true
		}
	}
	return false
}

func (m *Group) columnNames() []string {
	return []string{
		"id",
		"name",
		"path",
		"created_at",
		"updated_at",
	}
}
