// generated by argen; DO NOT EDIT
package db

import (
	"fmt"

	"github.com/monochromegane/argen"
)

type ProjectGroupRelation struct {
	src *ProjectGroup
	*ar.Relation
}

func (m *ProjectGroup) newRelation() *ProjectGroupRelation {
	r := &ProjectGroupRelation{
		m,
		ar.NewRelation(db, logger).Table("project_groups"),
	}
	r.Select(
		"id",
		"project_id",
		"group_id",
		"seq",
		"created_at",
		"updated_at",
	)

	return r
}

func (m ProjectGroup) Select(columns ...string) *ProjectGroupRelation {
	return m.newRelation().Select(columns...)
}

func (r *ProjectGroupRelation) Select(columns ...string) *ProjectGroupRelation {
	cs := []string{}
	for _, c := range columns {
		if r.src.isColumnName(c) {
			cs = append(cs, fmt.Sprintf("project_groups.%s", c))
		} else {
			cs = append(cs, c)
		}
	}
	r.Relation.Columns(cs...)
	return r
}

func (m ProjectGroup) Find(id int) (*ProjectGroup, error) {
	return m.newRelation().Find(id)
}

func (r *ProjectGroupRelation) Find(id int) (*ProjectGroup, error) {
	return r.FindBy("id", id)
}

func (m ProjectGroup) FindBy(cond string, args ...interface{}) (*ProjectGroup, error) {
	return m.newRelation().FindBy(cond, args...)
}

func (r *ProjectGroupRelation) FindBy(cond string, args ...interface{}) (*ProjectGroup, error) {
	return r.Where(cond, args...).Limit(1).QueryRow()
}

func (m ProjectGroup) First() (*ProjectGroup, error) {
	return m.newRelation().First()
}

func (r *ProjectGroupRelation) First() (*ProjectGroup, error) {
	return r.Order("id", "ASC").Limit(1).QueryRow()
}

func (m ProjectGroup) Last() (*ProjectGroup, error) {
	return m.newRelation().Last()
}

func (r *ProjectGroupRelation) Last() (*ProjectGroup, error) {
	return r.Order("id", "DESC").Limit(1).QueryRow()
}

func (m ProjectGroup) Where(cond string, args ...interface{}) *ProjectGroupRelation {
	return m.newRelation().Where(cond, args...)
}

func (r *ProjectGroupRelation) Where(cond string, args ...interface{}) *ProjectGroupRelation {
	r.Relation.Where(cond, args...)
	return r
}

func (r *ProjectGroupRelation) And(cond string, args ...interface{}) *ProjectGroupRelation {
	r.Relation.And(cond, args...)
	return r
}

func (m ProjectGroup) Order(column, order string) *ProjectGroupRelation {
	return m.newRelation().Order(column, order)
}

func (r *ProjectGroupRelation) Order(column, order string) *ProjectGroupRelation {
	r.Relation.OrderBy(column, order)
	return r
}

func (m ProjectGroup) Limit(limit int) *ProjectGroupRelation {
	return m.newRelation().Limit(limit)
}

func (r *ProjectGroupRelation) Limit(limit int) *ProjectGroupRelation {
	r.Relation.Limit(limit)
	return r
}

func (m ProjectGroup) Offset(offset int) *ProjectGroupRelation {
	return m.newRelation().Offset(offset)
}

func (r *ProjectGroupRelation) Offset(offset int) *ProjectGroupRelation {
	r.Relation.Offset(offset)
	return r
}

func (m ProjectGroup) Group(group string, groups ...string) *ProjectGroupRelation {
	return m.newRelation().Group(group, groups...)
}

func (r *ProjectGroupRelation) Group(group string, groups ...string) *ProjectGroupRelation {
	r.Relation.GroupBy(group, groups...)
	return r
}

func (r *ProjectGroupRelation) Having(cond string, args ...interface{}) *ProjectGroupRelation {
	r.Relation.Having(cond, args...)
	return r
}

func (m ProjectGroup) IsValid() (bool, *ar.Errors) {
	result := true
	errors := &ar.Errors{}
	var on ar.On
	if m.IsNewRecord() {
		on = ar.OnCreate()
	} else {
		on = ar.OnUpdate()
	}
	rules := map[string]*ar.Validation{}
	for name, rule := range rules {
		if ok, errs := ar.NewValidator(rule).On(on).IsValid(m.fieldValueByName(name)); !ok {
			result = false
			errors.SetErrors(name, errs)
		}
	}
	customs := []*ar.Validation{}
	for _, rule := range customs {
		custom := ar.NewValidator(rule).On(on).Custom()
		custom(errors)
	}
	if len(errors.Messages) > 0 {
		result = false
	}
	return result, errors
}

type ProjectGroupParams ProjectGroup

func (m ProjectGroup) Build(p ProjectGroupParams) *ProjectGroup {
	return &ProjectGroup{
		ID:        p.ID,
		ProjectID: p.ProjectID,
		GroupID:   p.GroupID,
		Seq:       p.Seq,
		CreatedAt: p.CreatedAt,
		UpdatedAt: p.UpdatedAt,
	}
}

func (m ProjectGroup) Create(p ProjectGroupParams) (*ProjectGroup, *ar.Errors) {
	n := m.Build(p)
	_, errs := n.Save()
	return n, errs
}

func (m *ProjectGroup) IsNewRecord() bool {
	return ar.IsZero(m.ID)
}

func (m *ProjectGroup) IsPersistent() bool {
	return !m.IsNewRecord()
}

func (m *ProjectGroup) Save(validate ...bool) (bool, *ar.Errors) {
	if len(validate) == 0 || len(validate) > 0 && validate[0] {
		if ok, errs := m.IsValid(); !ok {
			return false, errs
		}
	}
	errs := &ar.Errors{}
	if m.IsNewRecord() {
		ins := ar.NewInsert(db, logger).Table("project_groups").Params(map[string]interface{}{
			"project_id": m.ProjectID,
			"group_id":   m.GroupID,
			"seq":        m.Seq,
			"created_at": m.CreatedAt,
			"updated_at": m.UpdatedAt,
		})

		if result, err := ins.Exec(); err != nil {
			errs.AddError("base", err)
			return false, errs
		} else {
			if lastId, err := result.LastInsertId(); err == nil {
				m.ID = int(lastId)
			}
		}
		return true, nil
	} else {
		upd := ar.NewUpdate(db, logger).Table("project_groups").Params(map[string]interface{}{
			"id":         m.ID,
			"project_id": m.ProjectID,
			"group_id":   m.GroupID,
			"seq":        m.Seq,
			"created_at": m.CreatedAt,
			"updated_at": m.UpdatedAt,
		}).Where("id", m.ID)

		if _, err := upd.Exec(); err != nil {
			errs.AddError("base", err)
			return false, errs
		}
		return true, nil
	}
}

func (m *ProjectGroup) Update(p ProjectGroupParams) (bool, *ar.Errors) {

	if !ar.IsZero(p.ID) {
		m.ID = p.ID
	}
	if !ar.IsZero(p.ProjectID) {
		m.ProjectID = p.ProjectID
	}
	if !ar.IsZero(p.GroupID) {
		m.GroupID = p.GroupID
	}
	if !ar.IsZero(p.Seq) {
		m.Seq = p.Seq
	}
	if !ar.IsZero(p.CreatedAt) {
		m.CreatedAt = p.CreatedAt
	}
	if !ar.IsZero(p.UpdatedAt) {
		m.UpdatedAt = p.UpdatedAt
	}
	return m.Save()
}

func (m *ProjectGroup) UpdateColumns(p ProjectGroupParams) (bool, *ar.Errors) {

	if !ar.IsZero(p.ID) {
		m.ID = p.ID
	}
	if !ar.IsZero(p.ProjectID) {
		m.ProjectID = p.ProjectID
	}
	if !ar.IsZero(p.GroupID) {
		m.GroupID = p.GroupID
	}
	if !ar.IsZero(p.Seq) {
		m.Seq = p.Seq
	}
	if !ar.IsZero(p.CreatedAt) {
		m.CreatedAt = p.CreatedAt
	}
	if !ar.IsZero(p.UpdatedAt) {
		m.UpdatedAt = p.UpdatedAt
	}
	return m.Save(false)
}

func (m *ProjectGroup) Destroy() (bool, *ar.Errors) {
	return m.Delete()
}

func (m *ProjectGroup) Delete() (bool, *ar.Errors) {
	errs := &ar.Errors{}
	if _, err := ar.NewDelete(db, logger).Table("project_groups").Where("id", m.ID).Exec(); err != nil {
		errs.AddError("base", err)
		return false, errs
	}
	return true, nil
}

func (m ProjectGroup) DeleteAll() (bool, *ar.Errors) {
	errs := &ar.Errors{}
	if _, err := ar.NewDelete(db, logger).Table("project_groups").Exec(); err != nil {
		errs.AddError("base", err)
		return false, errs
	}
	return true, nil
}

func (r *ProjectGroupRelation) Query() ([]*ProjectGroup, error) {
	rows, err := r.Relation.Query()
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	results := []*ProjectGroup{}
	for rows.Next() {
		row := &ProjectGroup{}
		err := rows.Scan(row.fieldPtrsByName(r.Relation.GetColumns())...)
		if err != nil {
			return nil, err
		}
		results = append(results, row)
	}
	return results, nil
}

func (r *ProjectGroupRelation) QueryRow() (*ProjectGroup, error) {
	row := &ProjectGroup{}
	err := r.Relation.QueryRow(row.fieldPtrsByName(r.Relation.GetColumns())...)
	if err != nil {
		return nil, err
	}
	return row, nil
}

func (m ProjectGroup) Exists() bool {
	return m.newRelation().Exists()
}

func (m ProjectGroup) Count(column ...string) int {
	return m.newRelation().Count(column...)
}

func (m ProjectGroup) All() *ProjectGroupRelation {
	return m.newRelation().All()
}

func (r *ProjectGroupRelation) All() *ProjectGroupRelation {
	return r
}

func (m *ProjectGroup) fieldValueByName(name string) interface{} {
	switch name {
	case "id", "project_groups.id":
		return m.ID
	case "project_id", "project_groups.project_id":
		return m.ProjectID
	case "group_id", "project_groups.group_id":
		return m.GroupID
	case "seq", "project_groups.seq":
		return m.Seq
	case "created_at", "project_groups.created_at":
		return m.CreatedAt
	case "updated_at", "project_groups.updated_at":
		return m.UpdatedAt
	default:
		return ""
	}
}

func (m *ProjectGroup) fieldPtrByName(name string) interface{} {
	switch name {
	case "id", "project_groups.id":
		return &m.ID
	case "project_id", "project_groups.project_id":
		return &m.ProjectID
	case "group_id", "project_groups.group_id":
		return &m.GroupID
	case "seq", "project_groups.seq":
		return &m.Seq
	case "created_at", "project_groups.created_at":
		return &m.CreatedAt
	case "updated_at", "project_groups.updated_at":
		return &m.UpdatedAt
	default:
		return nil
	}
}

func (m *ProjectGroup) fieldPtrsByName(names []string) []interface{} {
	fields := []interface{}{}
	for _, n := range names {
		f := m.fieldPtrByName(n)
		fields = append(fields, f)
	}
	return fields
}

func (m *ProjectGroup) isColumnName(name string) bool {
	for _, c := range m.columnNames() {
		if c == name {
			return true
		}
	}
	return false
}

func (m *ProjectGroup) columnNames() []string {
	return []string{
		"id",
		"project_id",
		"group_id",
		"seq",
		"created_at",
		"updated_at",
	}
}
